const UPLOAD_PROFILE = 'UPLOAD_PROFILE';
const UPLOAD_PROFILE_NEWS = 'UPLOAD_PROFILE_NEWS';
const UPLOAD_PROFILE_NOTIFICATIONS = 'UPLOAD_PROFILE_NOTIFICATIONS';

const UPLOAD_POST = 'UPLOAD_POST';

export { UPLOAD_PROFILE, UPLOAD_PROFILE_NEWS, UPLOAD_PROFILE_NOTIFICATIONS, UPLOAD_POST };